services:
  backend:
    build:
      context: ./backend
    container_name: user-management-backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
    working_dir: /app
    command: ["go", "run", "main.go"]

  frontend:
    build:
      context: ./frontend
    container_name: user-management-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    working_dir: /app
    command: ["npm", "run", "dev"]

networks:
  default:
    driver: bridge